=begin comment

Direct Freight API

In order to use the Direct Freight API please first contact us to get an API Token. This token needs to be sent as a HTTP header argument in every request to our API.  api-token=\"SECRET KEY\"  Please keep your api-token a secret. If the token is compromised please contact us to get a new one.  This api token authenticates your application and gives it access to the API.  The API token should not be confused with the end-user-token. That token is given to you via the end_user_authentications endpoint when the user logs in. This token is needed in order to use certain features, and get certain sensitive information.  Both Tokens are stateless, and delivered via the HTTP headers.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::EnduserauthenticationsApi');

my $api = WWW::SwaggerClient::EnduserauthenticationsApi->new();
isa_ok($api, 'WWW::SwaggerClient::EnduserauthenticationsApi');

#
# end_user_authentication_users_post test
#
{
    my $body = undef; # replace NULL with a proper value
    my $result = $api->end_user_authentication_users_post(body => $body);
}

#
# end_user_authentications_dates_get test
#
{
    my $result = $api->end_user_authentications_dates_get();
}

#
# end_user_authentications_delete test
#
{
    my $ = undef; # replace NULL with a proper value
    my $end_user_token = undef; # replace NULL with a proper value
    my $result = $api->end_user_authentications_delete( => $, end_user_token => $end_user_token);
}

#
# end_user_authentications_get test
#
{
    my $ = undef; # replace NULL with a proper value
    my $end_user_token = undef; # replace NULL with a proper value
    my $result = $api->end_user_authentications_get( => $, end_user_token => $end_user_token);
}

#
# end_user_authentications_passwords_get test
#
{
    my $email = undef; # replace NULL with a proper value
    my $result = $api->end_user_authentications_passwords_get(email => $email);
}

#
# end_user_authentications_passwords_patch test
#
{
    my $body = undef; # replace NULL with a proper value
    my $end_user_token = undef; # replace NULL with a proper value
    my $result = $api->end_user_authentications_passwords_patch(body => $body, end_user_token => $end_user_token);
}

#
# end_user_authentications_post test
#
{
    my $ = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $result = $api->end_user_authentications_post( => $, body => $body);
}


1;
