=begin comment

Direct Freight API

In order to use the Direct Freight API please first contact us to get an API Token. This token needs to be sent as a HTTP header argument in every request to our API.  api-token=\"SECRET KEY\"  Please keep your api-token a secret. If the token is compromised please contact us to get a new one.  This api token authenticates your application and gives it access to the API.  The API token should not be confused with the end-user-token. That token is given to you via the end_user_authentications endpoint when the user logs in. This token is needed in order to use certain features, and get certain sensitive information.  Both Tokens are stateless, and delivered via the HTTP headers.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::EnduserauthenticationsApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;
use WWW::SwaggerClient::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => WWW::SwaggerClient::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# end_user_authentication_users_post
#
# Create a new user.
# 
# @param CreateUser $body  (required)
{
    my $params = {
    'body' => {
        data_type => 'CreateUser',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'end_user_authentication_users_post' } = { 
    	summary => 'Create a new user.',
        params => $params,
        returns => 'PostEndUserAuthenticationResponse',
        };
}
# @return PostEndUserAuthenticationResponse
#
sub end_user_authentication_users_post {
    my ($self, %args) = @_;

    # verify the required parameter 'body' is set
    unless (exists $args{'body'}) {
      croak("Missing the required parameter 'body' when calling end_user_authentication_users_post");
    }

    # parse inputs
    my $_resource_path = '/end_user_authentication/users';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PostEndUserAuthenticationResponse', $response);
    return $_response_object;
}

#
# end_user_authentications_dates_get
#
# Gets an authoritative date_time string.
# 
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'end_user_authentications_dates_get' } = { 
    	summary => 'Gets an authoritative date_time string.',
        params => $params,
        returns => 'GetEndUserAuthenticationsDatesResponse',
        };
}
# @return GetEndUserAuthenticationsDatesResponse
#
sub end_user_authentications_dates_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/end_user_authentications/dates';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GetEndUserAuthenticationsDatesResponse', $response);
    return $_response_object;
}

#
# end_user_authentications_delete
#
# Logs a user out.
# 
# @param string $ The logged in user&#39;s token. (required)
# @param string $end_user_token The logged in user&#39;s token. (optional)
{
    my $params = {
    '' => {
        data_type => 'string',
        description => 'The logged in user&#39;s token.',
        required => '1',
    },
    'end_user_token' => {
        data_type => 'string',
        description => 'The logged in user&#39;s token.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'end_user_authentications_delete' } = { 
    	summary => 'Logs a user out.',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub end_user_authentications_delete {
    my ($self, %args) = @_;

    # verify the required parameter '' is set
    unless (exists $args{''}) {
      croak("Missing the required parameter '' when calling end_user_authentications_delete");
    }

    # parse inputs
    my $_resource_path = '/end_user_authentications';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{''}) {
        $query_params->{''} = $self->{api_client}->to_query_value($args{''});
    }

    # header params
    if ( exists $args{'end_user_token'}) {
        $header_params->{'end-user-token'} = $self->{api_client}->to_header_value($args{'end_user_token'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# end_user_authentications_get
#
# Get current authentication level for the user.
# 
# @param string $ The logged in user&#39;s token. (required)
# @param string $end_user_token The logged in user&#39;s token. (required)
{
    my $params = {
    '' => {
        data_type => 'string',
        description => 'The logged in user&#39;s token.',
        required => '1',
    },
    'end_user_token' => {
        data_type => 'string',
        description => 'The logged in user&#39;s token.',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'end_user_authentications_get' } = { 
    	summary => 'Get current authentication level for the user.',
        params => $params,
        returns => 'GetEndUserAuthenticationsResponse',
        };
}
# @return GetEndUserAuthenticationsResponse
#
sub end_user_authentications_get {
    my ($self, %args) = @_;

    # verify the required parameter '' is set
    unless (exists $args{''}) {
      croak("Missing the required parameter '' when calling end_user_authentications_get");
    }

    # verify the required parameter 'end_user_token' is set
    unless (exists $args{'end_user_token'}) {
      croak("Missing the required parameter 'end_user_token' when calling end_user_authentications_get");
    }

    # parse inputs
    my $_resource_path = '/end_user_authentications';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{''}) {
        $query_params->{''} = $self->{api_client}->to_query_value($args{''});
    }

    # header params
    if ( exists $args{'end_user_token'}) {
        $header_params->{'end-user-token'} = $self->{api_client}->to_header_value($args{'end_user_token'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GetEndUserAuthenticationsResponse', $response);
    return $_response_object;
}

#
# end_user_authentications_passwords_get
#
# Request a forgotten password.
# 
# @param string $email The user e-mail to send a password to if valid. (required)
{
    my $params = {
    'email' => {
        data_type => 'string',
        description => 'The user e-mail to send a password to if valid.',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'end_user_authentications_passwords_get' } = { 
    	summary => 'Request a forgotten password.',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub end_user_authentications_passwords_get {
    my ($self, %args) = @_;

    # verify the required parameter 'email' is set
    unless (exists $args{'email'}) {
      croak("Missing the required parameter 'email' when calling end_user_authentications_passwords_get");
    }

    # parse inputs
    my $_resource_path = '/end_user_authentications/passwords';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'email'}) {
        $query_params->{'email'} = $self->{api_client}->to_query_value($args{'email'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# end_user_authentications_passwords_patch
#
# 
# 
# @param UpdatePassword $body  (required)
# @param string $end_user_token The logged in user&#39;s token. (required)
{
    my $params = {
    'body' => {
        data_type => 'UpdatePassword',
        description => '',
        required => '1',
    },
    'end_user_token' => {
        data_type => 'string',
        description => 'The logged in user&#39;s token.',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'end_user_authentications_passwords_patch' } = { 
    	summary => '',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub end_user_authentications_passwords_patch {
    my ($self, %args) = @_;

    # verify the required parameter 'body' is set
    unless (exists $args{'body'}) {
      croak("Missing the required parameter 'body' when calling end_user_authentications_passwords_patch");
    }

    # verify the required parameter 'end_user_token' is set
    unless (exists $args{'end_user_token'}) {
      croak("Missing the required parameter 'end_user_token' when calling end_user_authentications_passwords_patch");
    }

    # parse inputs
    my $_resource_path = '/end_user_authentications/passwords';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'PATCH';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # header params
    if ( exists $args{'end_user_token'}) {
        $header_params->{'end-user-token'} = $self->{api_client}->to_header_value($args{'end_user_token'});
    }

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

#
# end_user_authentications_post
#
# Logs a user in.
# 
# @param string $ The logged in user&#39;s token. (required)
# @param Login $body  (required)
{
    my $params = {
    '' => {
        data_type => 'string',
        description => 'The logged in user&#39;s token.',
        required => '1',
    },
    'body' => {
        data_type => 'Login',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'end_user_authentications_post' } = { 
    	summary => 'Logs a user in.',
        params => $params,
        returns => 'PostEndUserAuthenticationResponse',
        };
}
# @return PostEndUserAuthenticationResponse
#
sub end_user_authentications_post {
    my ($self, %args) = @_;

    # verify the required parameter '' is set
    unless (exists $args{''}) {
      croak("Missing the required parameter '' when calling end_user_authentications_post");
    }

    # verify the required parameter 'body' is set
    unless (exists $args{'body'}) {
      croak("Missing the required parameter 'body' when calling end_user_authentications_post");
    }

    # parse inputs
    my $_resource_path = '/end_user_authentications';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{''}) {
        $query_params->{''} = $self->{api_client}->to_query_value($args{''});
    }

    my $_body_data;
    # body params
    if ( exists $args{'body'}) {
        $_body_data = $args{'body'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('PostEndUserAuthenticationResponse', $response);
    return $_response_object;
}

1;
