=begin comment

Direct Freight API

In order to use the Direct Freight API please first contact us to get an API Token. This token needs to be sent as a HTTP header argument in every request to our API.  api-token=\"SECRET KEY\"  Please keep your api-token a secret. If the token is compromised please contact us to get a new one.  This api token authenticates your application and gives it access to the API.  The API token should not be confused with the end-user-token. That token is given to you via the end_user_authentications endpoint when the user logs in. This token is needed in order to use certain features, and get certain sensitive information.  Both Tokens are stateless, and delivered via the HTTP headers.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::LocationsApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;
use WWW::SwaggerClient::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => WWW::SwaggerClient::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# location_distance_get
#
# Get the distance between 2 locations. This is used to calculate dead head miles.
# 
# @param string $origin_city  (required)
# @param string $origin_state  (required)
# @param string $destination_city  (required)
# @param string $destination_state  (required)
{
    my $params = {
    'origin_city' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'origin_state' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'destination_city' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    'destination_state' => {
        data_type => 'string',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'location_distance_get' } = { 
    	summary => 'Get the distance between 2 locations. This is used to calculate dead head miles.',
        params => $params,
        returns => 'GetLocationDistanceResponse',
        };
}
# @return GetLocationDistanceResponse
#
sub location_distance_get {
    my ($self, %args) = @_;

    # verify the required parameter 'origin_city' is set
    unless (exists $args{'origin_city'}) {
      croak("Missing the required parameter 'origin_city' when calling location_distance_get");
    }

    # verify the required parameter 'origin_state' is set
    unless (exists $args{'origin_state'}) {
      croak("Missing the required parameter 'origin_state' when calling location_distance_get");
    }

    # verify the required parameter 'destination_city' is set
    unless (exists $args{'destination_city'}) {
      croak("Missing the required parameter 'destination_city' when calling location_distance_get");
    }

    # verify the required parameter 'destination_state' is set
    unless (exists $args{'destination_state'}) {
      croak("Missing the required parameter 'destination_state' when calling location_distance_get");
    }

    # parse inputs
    my $_resource_path = '/location/distance';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'origin_city'}) {
        $query_params->{'origin_city'} = $self->{api_client}->to_query_value($args{'origin_city'});
    }

    # query params
    if ( exists $args{'origin_state'}) {
        $query_params->{'origin_state'} = $self->{api_client}->to_query_value($args{'origin_state'});
    }

    # query params
    if ( exists $args{'destination_city'}) {
        $query_params->{'destination_city'} = $self->{api_client}->to_query_value($args{'destination_city'});
    }

    # query params
    if ( exists $args{'destination_state'}) {
        $query_params->{'destination_state'} = $self->{api_client}->to_query_value($args{'destination_state'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GetLocationDistanceResponse', $response);
    return $_response_object;
}

#
# locations_closest_city_get
#
# Will return the closest city to a lat/lon point.
# 
# @param double $latitude  (required)
# @param double $longitude  (required)
{
    my $params = {
    'latitude' => {
        data_type => 'double',
        description => '',
        required => '1',
    },
    'longitude' => {
        data_type => 'double',
        description => '',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'locations_closest_city_get' } = { 
    	summary => 'Will return the closest city to a lat/lon point.',
        params => $params,
        returns => 'GetClosestCityResponse',
        };
}
# @return GetClosestCityResponse
#
sub locations_closest_city_get {
    my ($self, %args) = @_;

    # verify the required parameter 'latitude' is set
    unless (exists $args{'latitude'}) {
      croak("Missing the required parameter 'latitude' when calling locations_closest_city_get");
    }

    # verify the required parameter 'longitude' is set
    unless (exists $args{'longitude'}) {
      croak("Missing the required parameter 'longitude' when calling locations_closest_city_get");
    }

    # parse inputs
    my $_resource_path = '/locations/closest_city';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'latitude'}) {
        $query_params->{'latitude'} = $self->{api_client}->to_query_value($args{'latitude'});
    }

    # query params
    if ( exists $args{'longitude'}) {
        $query_params->{'longitude'} = $self->{api_client}->to_query_value($args{'longitude'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('GetClosestCityResponse', $response);
    return $_response_object;
}

#
# locations_partial_match_get
#
# A string of a partial city or state name, and returns a list of possible matches.
# 
# @param string $term Min 2 characters. (required)
# @param string $search_type \&quot;state\&quot;, and \&quot;city\&quot; will return only returns only the respective information for that search type. Misspelling, will default to city. (optional)
{
    my $params = {
    'term' => {
        data_type => 'string',
        description => 'Min 2 characters.',
        required => '1',
    },
    'search_type' => {
        data_type => 'string',
        description => '\&quot;state\&quot;, and \&quot;city\&quot; will return only returns only the respective information for that search type. Misspelling, will default to city.',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'locations_partial_match_get' } = { 
    	summary => 'A string of a partial city or state name, and returns a list of possible matches.',
        params => $params,
        returns => undef,
        };
}
# @return void
#
sub locations_partial_match_get {
    my ($self, %args) = @_;

    # verify the required parameter 'term' is set
    unless (exists $args{'term'}) {
      croak("Missing the required parameter 'term' when calling locations_partial_match_get");
    }

    # parse inputs
    my $_resource_path = '/locations/partial_match';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'term'}) {
        $query_params->{'term'} = $self->{api_client}->to_query_value($args{'term'});
    }

    # query params
    if ( exists $args{'search_type'}) {
        $query_params->{'search_type'} = $self->{api_client}->to_query_value($args{'search_type'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(api_key )];

    # make the API Call
    $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    return;
}

1;
