=begin comment

Direct Freight API

In order to use the Direct Freight API please first contact us to get an API Token. This token needs to be sent as a HTTP header argument in every request to our API.  api-token=\"SECRET KEY\"  Please keep your api-token a secret. If the token is compromised please contact us to get a new one.  This api token authenticates your application and gives it access to the API.  The API token should not be confused with the end-user-token. That token is given to you via the end_user_authentications endpoint when the user logs in. This token is needed in order to use certain features, and get certain sensitive information.  Both Tokens are stateless, and delivered via the HTTP headers.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::Object::PostObjectModel;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Direct Freight API

In order to use the Direct Freight API please first contact us to get an API Token. This token needs to be sent as a HTTP header argument in every request to our API.  api-token=\"SECRET KEY\"  Please keep your api-token a secret. If the token is compromised please contact us to get a new one.  This api token authenticates your application and gives it access to the API.  The API token should not be confused with the end-user-token. That token is given to you via the end_user_authentications endpoint when the user logs in. This token is needed in order to use certain features, and get certain sensitive information.  Both Tokens are stateless, and delivered via the HTTP headers.

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::SwaggerClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'PostObjectModel',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'comment' => {
    	datatype => 'object',
    	base_name => 'comment',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'custom_id' => {
    	datatype => 'object',
    	base_name => 'custom_id',
    	description => 'A unique identifier a user can provide for their own records.',
    	format => '',
    	read_only => '',
    		},
    'destination_city' => {
    	datatype => 'object',
    	base_name => 'destination_city',
    	description => 'For truck type entries this is optional.',
    	format => '',
    	read_only => '',
    		},
    'destination_state' => {
    	datatype => 'object',
    	base_name => 'destination_state',
    	description => 'For truck type entries this is optional.',
    	format => '',
    	read_only => '',
    		},
    'height' => {
    	datatype => 'object',
    	base_name => 'height',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'length' => {
    	datatype => 'object',
    	base_name => 'length',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'load_size' => {
    	datatype => 'object',
    	base_name => 'load_size',
    	description => 'Require for load type entries only. This field expects one of the 2 following terms, full or partial.',
    	format => '',
    	read_only => '',
    		},
    'origin_city' => {
    	datatype => 'object',
    	base_name => 'origin_city',
    	description => 'Required for all entry types.',
    	format => '',
    	read_only => '',
    		},
    'origin_state' => {
    	datatype => 'object',
    	base_name => 'origin_state',
    	description => 'Required, 2 character limit.',
    	format => '',
    	read_only => '',
    		},
    'other_trailer_types' => {
    	datatype => 'object',
    	base_name => 'other_trailer_types',
    	description => 'This may be empty.',
    	format => '',
    	read_only => '',
    		},
    'pay_rate' => {
    	datatype => 'object',
    	base_name => 'pay_rate',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'posting_id' => {
    	datatype => 'int',
    	base_name => 'posting_id',
    	description => 'A unique id in our system for the user&#39;s entry.',
    	format => '',
    	read_only => '',
    		},
    'receive_date' => {
    	datatype => 'object',
    	base_name => 'receive_date',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'ship_date' => {
    	datatype => 'object',
    	base_name => 'ship_date',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'trailer_type' => {
    	datatype => 'object',
    	base_name => 'trailer_type',
    	description => 'This can have 1 or more standard trailer types.',
    	format => '',
    	read_only => '',
    		},
    'weight' => {
    	datatype => 'object',
    	base_name => 'weight',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'width' => {
    	datatype => 'object',
    	base_name => 'width',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'comment' => 'object',
    'custom_id' => 'object',
    'destination_city' => 'object',
    'destination_state' => 'object',
    'height' => 'object',
    'length' => 'object',
    'load_size' => 'object',
    'origin_city' => 'object',
    'origin_state' => 'object',
    'other_trailer_types' => 'object',
    'pay_rate' => 'object',
    'posting_id' => 'int',
    'receive_date' => 'object',
    'ship_date' => 'object',
    'trailer_type' => 'object',
    'weight' => 'object',
    'width' => 'object'
} );

__PACKAGE__->attribute_map( {
    'comment' => 'comment',
    'custom_id' => 'custom_id',
    'destination_city' => 'destination_city',
    'destination_state' => 'destination_state',
    'height' => 'height',
    'length' => 'length',
    'load_size' => 'load_size',
    'origin_city' => 'origin_city',
    'origin_state' => 'origin_state',
    'other_trailer_types' => 'other_trailer_types',
    'pay_rate' => 'pay_rate',
    'posting_id' => 'posting_id',
    'receive_date' => 'receive_date',
    'ship_date' => 'ship_date',
    'trailer_type' => 'trailer_type',
    'weight' => 'weight',
    'width' => 'width'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
