get:
  parameters:
    - $ref: '#/parameters/end-user-token'
    - in: query
      items:
        type: integer
      name: posting_id
      required: false
      type: array
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_model'
  summary: STAGE=UNK Request the logged in user's profile.
  tags:
    - profiles
patch:
  consumes: []
  description: Please send in at least one field to be updated.
  parameters:
    - $ref: '#/parameters/end-user-token'
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/patch_profile'
  responses:
    '204':
      description: successful operation
  summary: STAGE=UNK Update profile information.
  tags:
    - profiles
post:
  consumes: []
  parameters:
    - $ref: '#/parameters/end-user-token'
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/profile_request'
  responses:
    '201':
      description: Object created check the headers for a reference URL.
      headers:
        Location:
          description: >-
            This will have a fully qualified API url you can call to get details
            of yoru load.
          type: string
          x-example: 'https://directfreight.com/api/postings/loads/?posting_id=1764957218'
      schema:
        properties:
          success:
            type: boolean
        type: object
  summary: STAGE=UNK Create a new profile.
  tags:
    - profiles
x-restlet:
  section: PROFILES
