get:
  parameters:
    - $ref: '#/parameters/end-user-token'
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_model'
  summary: Request the logged in user's profile.
  tags:
    - profiles
patch:
  description: Please send in at least one field to be updated.
  parameters:
    - $ref: '#/parameters/end-user-token'
    - in: body
      name: body
      required: false
      schema:
        $ref: '#/definitions/patch_profile'
  responses:
    '204':
      description: successful operation
  summary: Update profile information.
  tags:
    - profiles
post:
  parameters:
    - $ref: '#/parameters/end-user-token'
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/create_profile'
  responses:
    '201':
      $ref: '#/responses/object_created'
  summary: Create a new profile.
  tags:
    - profiles
