delete:
  parameters:
    - in: header
      name: end-user-token
      required: true
      type: string
  responses:
    '204':
      description: success operation
  summary: STAGE=UNK Delete the profile.
  tags:
    - profiles
get:
  parameters:
    - in: header
      name: end-user-token
      required: true
      type: string
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_object'
  summary: Request the logged in user's profile.
  tags:
    - profiles
patch:
  description: Please send in at least one field to be updated.
  parameters:
    - in: header
      name: end-user-token
      required: true
      type: string
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/profile_object_patch'
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_object_patch'
  summary: Update profile information.
  tags:
    - profiles
post:
  parameters:
    - in: header
      name: end-user-token
      required: true
      type: string
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/profile_object'
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_object_patch'
  summary: Create a new profile.
  tags:
    - profiles
x-restlet:
  section: PROFILES
