get:
  parameters:
    - $ref: '#/parameters/end-user-token'
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_model'
  summary: Request the logged in user's profile.
  tags:
    - profiles
patch:
  parameters:
    - $ref: '#/parameters/end-user-token'
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/patch_profile'
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_model'
  summary: Update profile information.
  tags:
    - profiles
post:
  parameters:
    - $ref: '#/parameters/end-user-token'
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/create_profile'
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/success_success_response'
  summary: Create a new profile.
  tags:
    - profiles
