---
get:
  consumes:
  - application/json
  parameters:
  - description: The logged in profile's token.
    in: header
    name: end-user-token
    required: true
    type: string
  produces:
  - application/json
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_model'
  summary: Request the logged in user's profile.
  tags:
  - profiles
patch:
  consumes:
  - application/json
  parameters:
  - description: The logged in profile's token.
    in: header
    name: end-user-token
    required: true
    type: string
  - in: body
    name: body
    required: true
    schema:
      $ref: '#/definitions/patch_profile'
  produces:
  - application/json
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/profile_model'
  summary: Update profile information.
  tags:
  - profiles
post:
  consumes:
  - application/json
  parameters:
  - description: The logged in profile's token.
    in: header
    name: end-user-token
    required: true
    type: string
  - in: body
    name: body
    required: true
    schema:
      $ref: '#/definitions/create_profile'
  produces:
  - application/json
  responses:
    '200':
      description: successful operation
      schema:
        $ref: '#/definitions/success_success_response'
  summary: Create a new profile.
  tags:
  - profiles
