get:
  parameters:
    - in: header
      name: end-user-token
      required: true
      type: string
  responses:
    '200':
      description: Status 200
      schema:
        $ref: '#/definitions/profile_response'
  summary: STAGE=UNK Get their profile
  tags:
    - profiles
patch:
  consumes: []
  parameters:
    - in: header
      name: end-user-token
      required: true
      type: string
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/profile_request'
  responses:
    '200':
      description: Status 200
      schema:
        $ref: '#/definitions/profile_patch_response'
  summary: STAGE=UNK Update a profile.
  tags:
    - profiles
post:
  consumes: []
  parameters:
    - in: header
      name: end-user-token
      required: true
      type: string
    - in: body
      name: body
      required: true
      schema:
        $ref: '#/definitions/profile_request'
  responses:
    '201':
      description: Status 201
      headers:
        url:
          type: string
  summary: STAGE=UNK Create a profile
  tags:
    - profiles
x-restlet:
  section: PROFILES
